title: Blog of a Code Fool
description: Irregular blog of Clifford W. Johnson
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - blog.iml
keep_files: [images]
asciidoc:
  processor: asciidoctor
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    idseparator: _
    source-highlighter: coderay@
    icons: font
    imagesdir: /images
