= Random Musings of a Code Fool
:showtitle:
:page-title: The Irregular BLOG of Clifford W. Johnson
:page-description: Anchor page for blog including credits.
:page-liquid:

// > jekyll serve
// > open http://localhost:4000

Welcome to the blog of a sometimes misguided, peculiar, _old_ programmer.  Postings will be irregular and on topics
that, at one point in time, piqued my interest enough so I couldn't drag myself away to work on my real job.

The site is, itself, an experiment
hosted on https://github.com/cljohnso/cljohnso.github.io[GitHub]
making use of http://jekyllrb.com[Jekyll] and
the AsciiDoc https://github.com/asciidoctor/jekyll-asciidoc-quickstart[*Jekyll AsciiDoc Quickstart*] project.
(At some point in time, I'll post a blog entry detailing this.)  As I learn about the tools I'm using and
about others available, the shape of the content will change.

== Recent Posts

{% for post in site.posts limit: 5 %}
* link:.{{ post.url }}[{{ post.navtitle }}]
{% endfor %}

== Credit where credit is due

The following are links to the software on which which blog is based:

* http://jekyllrb.com[Jekyll]
* http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick Reference]
* http://asciidoctor.org[Asciidoctor]
* https://github.com/asciidoctor/jekyll-asciidoc-quickstart[*Jekyll AsciiDoc Quickstart*]
* http://foundation.zurb.com[Foundation]